AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: AWS SAM template for twentyfour-hour-video service

Globals:
  Function:
    Runtime: nodejs18.x
    Environment:
      Variables:
        MEDIA_ENDPOINT: "https://lxlxpswfb.mediaconvert.us-east-1.amazonaws.com"
        MEDIA_ROLE: "arn:aws:iam::064592191516:role/media-convert-role"
        TRANSCODED_VIDEO_BUCKET: "064592191516-serverless-video-transcode"

Resources:
  TranscodeVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: transcode-video/index.handler
      Role: arn:aws:iam::064592191516:role/transcode-video
      PackageType: Individual
      Events:
        S3Event:
          Type: S3
          Properties:
            Events: "s3:ObjectCreated:*"
            Bucket: "064592191516-serverless-video-transcode"

Outputs:
  TranscodeVideoFunctionArn:
    Description: "ARN of the transcode-video Lambda function"
    Value:
      Fn::GetAtt:
        - TranscodeVideoFunction
        - Arn
