service: twentyfour-hour-video
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

functions:
  transcode-video:
    handler: transcode-video/index.handler
    role: "arn:aws:iam::064592191516:role/transcode-video"
    package:
      individually: true
    environment:
      MEDIA_ENDPOINT: "https://lxlxpswfb.mediaconvert.us-east-1.amazonaws.com"
      MEDIA_ROLE: "arn:aws:iam::064592191516:role/media-convert-role"
      TRANSCODED_VIDEO_BUCKET: "064592191516-serverless-video-transcode"
    events:
      - s3: "064592191516-serverless-video-upload"