init:
	sudo npm install -g serverless
	sudo npm install -g serverless-offline
	sls config credentials --provider aws --key <> --secret <>

serverless.yml:
	sls create --template aws-python3 --path .

.serverless/twentyfour-hour-video-python.zip:
	sls deploy