service: twentyfour-hour-video-python
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev

functions:
  transcode-video:
    handler: transcode_video_python/__main__.lambda_handler
    role: "arn:aws:iam::064592191516:role/transcode-video"
    package:
      individually: true
    environment:
      MEDIA_ENDPOINT: "https://lxlxpswfb.mediaconvert.us-east-1.amazonaws.com"
      MEDIA_ROLE: "arn:aws:iam::064592191516:role/media-convert-role"
      TRANSCODED_VIDEO_BUCKET: "064592191516-serverless-video-transcode-python"
    events:
      - s3:
          bucket: "064592191516-serverless-video-upload-python"
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
          existing: true